#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlamthIrrigationDistrict.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KIDTEMPLATE")]
	public partial class KIDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public KIDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KIDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KIDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KIDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Cusomters_InsertUpdate")]
		public int sp_Cusomters_InsertUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerFirstName", DbType="VarChar(50)")] string customerFirstName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerLastName", DbType="VarChar(50)")] string customerLastName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="VarChar(100)")] string address1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="VarChar(100)")] string address2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="VarChar(50)")] string city, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="VarChar(2)")] string state, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zip", DbType="Int")] System.Nullable<int> zip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerPhoneNumber", DbType="VarChar(10)")] string customerPhoneNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerEmail", DbType="VarChar(255)")] string customerEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, customerFirstName, customerLastName, address1, address2, city, state, zip, customerPhoneNumber, customerEmail);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CustomerHistory_GetList")]
		public ISingleResult<sp_CustomerHistory_GetListResult> sp_CustomerHistory_GetList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_CustomerHistory_GetListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CustomerRequest_CreateDelete")]
		public int sp_CustomerRequest_CreateDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaterAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> waterAmount, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaterOnDate", DbType="Date")] System.Nullable<System.DateTime> waterOnDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaterOffDate", DbType="Date")] System.Nullable<System.DateTime> waterOffDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="VarChar(255)")] string comments)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), waterAmount, waterOnDate, waterOffDate, comments);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_CustomerRequest_SetWaterTImes")]
		public int sp_CustomerRequest_SetWaterTImes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaterOn", DbType="Date")] System.Nullable<System.DateTime> waterOn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WaterOff", DbType="Date")] System.Nullable<System.DateTime> waterOff)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), waterOn, waterOff);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_CustomerHistory_GetListResult
	{
		
		private int _CustomerHistoryID;
		
		private int _CustomerID;
		
		private System.DateTime _Date;
		
		private decimal _WaterUsage;
		
		public sp_CustomerHistory_GetListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerHistoryID", DbType="Int NOT NULL")]
		public int CustomerHistoryID
		{
			get
			{
				return this._CustomerHistoryID;
			}
			set
			{
				if ((this._CustomerHistoryID != value))
				{
					this._CustomerHistoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WaterUsage", DbType="Decimal(18,0) NOT NULL")]
		public decimal WaterUsage
		{
			get
			{
				return this._WaterUsage;
			}
			set
			{
				if ((this._WaterUsage != value))
				{
					this._WaterUsage = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
